name: FruitAPI
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - Allfiles/Labs/01/FruitAPI/**

defaults:
  run:
    shell: pwsh

jobs:
  create_zip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Create Fruit zip
      run: zip -r -q FruitAPI.zip Allfiles/Labs/01/FruitAPI/**
    
  
