name: FruitWebApp Start
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - Allfiles/Labs/01/FruitWebApp-start/**

defaults:
  run:
    shell: pwsh

jobs:
  create_zip:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Create Fruit zip
      run: | 
        cd ./Allfiles/Labs/01
        zip -r -q ../../Downloads/FruitWebApp-start.zip FruitWebApp-start/*
    - name: Commit and push
      uses: Endbug/add-and-commit@v7
      with:
        add: '["Allfiles/Downloads/FruitWebApp-start.zip"]'
        message: 'Updating Zip for API source files'
        push: true
